services:
  - type: web
    name: medivend-fullstack
    env: node
    rootDir: .
    plan: free
    buildCommand: npm --prefix client install --include=dev ; npm --prefix server install ; npm --prefix client run build
    startCommand: npm --prefix server start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AUTO_SEED_ON_START
        value: true
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: medivend
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: LOW_STOCK_THRESHOLD
        value: 10
      - key: EXPIRY_ALERT_DAYS
        value: 30
      - key: MAX_TEMP
        value: 35
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
